export enum CategoryError {
    EMPTY_LEVELS = "EMPTY_LEVELS",
    ROOT_NOT_FOUND = "ROOT_NOT_FOUND",
    CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND",
    CATEGORY_HAS_CHILDREN = "CATEGORY_HAS_CHILDREN"
}