export enum TenantError {
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  SLUG_ALREADY_EXISTS = "SLUG_ALREADY_EXISTS",
  TENANT_NOT_FOUND = "TENANT_NOT_FOUND",
  REGISTRATION_DISABLED = "REGISTRATION_DISABLED",
  INVALID_SLUG = "INVALID_SLUG",
  ALREADY_EXISTS = "ALREADY_EXISTS",
  INVALID_INVITE = "INVALID_INVITE",
  INVITE_EXPIRED = "INVITE_EXPIRED",
  INVITE_EMAIL_MISMATCH = "INVITE_EMAIL_MISMATCH",
  FISCAL_CONFIG_NOT_FOUND = "FISCAL_CONFIG_NOT_FOUND",
  FISCAL_RANGE_INVALID    = "FISCAL_RANGE_INVALID",
}